name: doclayout_yolo
owner: bgruening
description: Tool for segmenting text in images.
long_description: Tool for segmenting text in images using Yolo model pretrained on large number of documents.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/
homepage_url: https://github.com/bgruening/galaxytools
type:
categories:
  - Machine Learning
  - Imaging
maintainers:
  - anuprulez
