name: doclayout_yolo
owner: bgruening
description: Enhancing Document Layout Analysis.
long_description: |
   Enhancing Document Layout Analysis through Diverse Synthetic Data and Global-to-Local Adaptive Perception.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/yolo/
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/yolo/
type:
categories:
  - Machine Learning
  - Imaging
maintainers:
  - anuprulez
